version: '3.9'

services:
  web:
    container_name: mmv-dashboard
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./log:/app/log
      - ./tmp:/app/tmp
      - ./public/downloads:/app/public/downloads