default: &default
  adapter: mysql2
  encoding: utf8
  username: deploy
  password: Riskcovry@123
  port: 3306

production:
  primary:
    <<: *default
    host: <%= ENV["DATABASE_HOST"] %>
    database: riskcovry_qa
  medical:
    <<: *default
    host: 10.4.234.9
    database: riskcovry_medical_qa
  vehicle:
    <<: *default
    host: 10.4.234.9
    database: riskcovry_vehicle_qa
  homebiz:
    <<: *default
    host: 10.4.234.9
    database: riskcovry_homebiz_qa
  claim:
    <<: *default
    host: 10.4.234.9
    database: riskcovry_claims_qa
  location:
    <<: *default
    host: 10.4.234.9
    database: riskcovry_location_qa
